class ExcelData(object):

    def __init__(self, ):
        self.main_category = ''
        self.main_category_cell_letter = 'G'
        self.sub_category = ''
        self.sub_category_cell_letter = 'H'
        self.product_title = ''
        self.product_title_cell_letter = 'B'
        self.product_id = ''
        self.product_id_cell_letter = 'A'
        self.price_text = ''
        self.price_text_cell_letter = 'E'
        self.old_price_text = ''
        self.old_price_text_cell_letter = 'F'
        self.description = ''
        self.description_cell_letter = 'C'
        self.alcohol_concentration = ''
        self.alcohol_concentration_cell_letter = 'I'
        self.brand = ''
        self.brand_cell_letter = 'D'
        self.image_url = ''
        self.image_url_cell_letter = 'J'
        self.time = ''
        self.time_letter = 'K'
        self.time_difference = ''
        self.time_difference_letter = 'L'
